import js from '@eslint/js';
import tseslint from '@typescript-eslint/eslint-plugin';
// @ts-ignore
import tsparser from '@typescript-eslint/parser';
import type { Linter } from 'eslint';
// @ts-ignore
import eslintConfigPrettier from 'eslint-config-prettier';
import i18next from 'eslint-plugin-i18next';
import importPlugin from 'eslint-plugin-import';
import noSecrets from 'eslint-plugin-no-secrets';
// @ts-ignore
import promise from 'eslint-plugin-promise';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import unicorn from 'eslint-plugin-unicorn';
import globals from 'globals';

export default [
  {
    files: ['**/*.{js,mjs,cjs,ts,jsx,tsx}'],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
      globals: { ...globals.browser, ...globals.node },
    },
  },
  { ignores: ['**/node_modules/**', '**/dist/**', '**/coverage/**'] },
  {
    rules: {
      ...js.configs.recommended.rules,
      'no-var': 'warn',
      'prefer-const': 'warn',
      'no-self-assign': 'warn',
      // 'no-unused-vars': ['warn', { varsIgnorePattern: '^_' }],
      'no-unused-vars': 'off',
      'no-undef': 'warn',
      'no-unsafe-optional-chaining': 'warn',
      camelcase: 'warn',
      'array-callback-return': 'warn',
      'no-await-in-loop': 'off',
      'no-constructor-return': 'warn',
      'no-duplicate-imports': 'warn',
      'no-inner-declarations': 'warn',
      'no-promise-executor-return': 'warn',
      'no-self-compare': 'warn',
      'no-template-curly-in-string': 'warn',
      'no-unmodified-loop-condition': 'warn',
      'no-unreachable-loop': 'warn',
      'no-use-before-define': 'warn',
      'no-useless-assignment': 'warn',
      'require-atomic-updates': 'warn',
      'consistent-return': 'warn',
      'default-case': 'warn',
      'default-case-last': 'warn',
      'dot-notation': 'warn',
      eqeqeq: 'warn',
      complexity: ['warn', 10],
      'max-depth': ['warn', 4],
      'max-lines': ['warn', 1000],
      'max-lines-per-function': ['warn', 500],
      'max-params': ['warn', 10],
      'max-statements': ['warn', 50],
    },
  },
  {
    plugins: {
      '@typescript-eslint': tseslint,
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['warn', { varsIgnorePattern: '^_', argsIgnorePattern: '^_' }],
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-non-null-asserted-optional-chain': 'off',
    },
  },
  {
    plugins: { 'no-secrets': noSecrets },
    rules: {
      'no-secrets/no-secrets': ['warn', { tolerance: 4.5 }],
    },
  },
  {
    plugins: { react: react, 'react-hooks': reactHooks },
    rules: {
      ...react.configs.recommended.rules,
      'react/destructuring-assignment': 'warn',
      'react/no-children-prop': 'warn',
      'react/prop-types': 'off',
      'react/display-name': 'warn',
      'react/jsx-key': 'warn',
      'react/jsx-no-useless-fragment': 'warn',
      'react/jsx-no-undef': 'warn',
      'react-hooks/rules-of-hooks': 'warn',
      'react/hook-use-state': 'warn',
      'react/function-component-definition': 'warn',
      'react/iframe-missing-sandbox': 'warn',
      'react/jsx-boolean-value': 'warn',
      'react/jsx-child-element-spacing': 'warn',
      'react/jsx-curly-brace-presence': 'warn',
      'react/jsx-curly-spacing': 'warn',
      'react/jsx-fragments': ['warn', 'syntax'],
      'react/jsx-handler-names': 'off',
      'react/jsx-max-depth': ['warn', { max: 6 }],
      'react/jsx-no-comment-textnodes': 'warn',
      'react/jsx-no-duplicate-props': 'warn',
      'react/jsx-no-script-url': 'warn',
      'react/jsx-no-literals': 'off',
      'react/jsx-no-target-blank': ['warn', { enforceDynamicLinks: 'always' }],
      'react/jsx-one-expression-per-line': 'warn',
      'react/jsx-pascal-case': 'warn',
      'react/jsx-props-no-multi-spaces': 'warn',
      'react/jsx-props-no-spread-multi': 'warn',
      'react/jsx-uses-react': 'warn',
      'react/jsx-uses-vars': 'warn',
      'react/no-array-index-key': 'warn',
      'react/no-arrow-function-lifecycle': 'warn',
      'react/no-danger': 'warn',
      'react/no-deprecated': 'warn',
      'react/no-danger-with-children': 'warn',
      'react/no-direct-mutation-state': 'warn',
      'react/no-did-update-set-state': 'warn',
      'react/no-invalid-html-attribute': 'warn',
      'react/no-string-refs': 'warn',
      'react/no-typos': 'warn',
      'react/no-unescaped-entities': 'warn',
      'react/no-unknown-property': 'warn',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },
  {
    plugins: { promise: promise },
    rules: {
      'promise/always-return': 'warn',
      'promise/avoid-new': 'warn',
      'promise/catch-or-return': 'warn',
      'promise/no-callback-in-promise': 'warn',
      'promise/no-multiple-resolved': 'warn',
      'promise/no-native': 'off',
      'promise/no-nesting': 'warn',
      'promise/no-new-statics': 'warn',
      'promise/no-promise-in-callback': 'warn',
      'promise/no-return-in-finally': 'warn',
      'promise/no-return-wrap': 'warn',
      'promise/param-names': 'warn',
      'promise/prefer-await-to-callbacks': 'off',
      'promise/prefer-await-to-then': 'warn',
      'promise/prefer-catch': 'warn',
      'promise/spec-only': 'warn',
      'promise/valid-params': 'warn',
    },
  },
  {
    plugins: { unicorn: unicorn },
    rules: {
      'unicorn/better-regex': 'warn',
      'unicorn/catch-error-name': 'warn',
      'unicorn/consistent-destructuring': 'warn',
      'unicorn/consistent-existence-index-check': 'warn',
      'unicorn/consistent-function-scoping': 'warn',
      'unicorn/custom-error-definition': 'warn',
      'unicorn/empty-brace-spaces': 'warn',
      'unicorn/error-message': 'warn',
      'unicorn/escape-case': 'warn',
      'unicorn/expiring-todo-comments': 'off',
      'unicorn/explicit-length-check': 'warn',
      'unicorn/filename-case': ['warn', { cases: { camelCase: true, pascalCase: true, kebabCase: false, snakeCase: false } }],
      'unicorn/import-style': 'warn',
      'unicorn/new-for-builtins': 'warn',
      'unicorn/no-abusive-eslint-disable': 'warn',
      'unicorn/no-anonymous-default-export': 'warn',
      'unicorn/no-array-callback-reference': 'warn',
      'unicorn/no-array-for-each': 'warn',
      'unicorn/no-array-method-this-argument': 'warn',
      'unicorn/no-array-push-push': 'warn',
      'unicorn/no-array-reduce': 'off',
      'unicorn/no-await-expression-member': 'warn',
      'unicorn/no-await-in-promise-methods': 'warn',
      'unicorn/no-console-spaces': 'warn',
      'unicorn/no-document-cookie': 'warn',
      'unicorn/no-empty-file': 'warn',
      'unicorn/no-for-loop': 'warn',
      'unicorn/no-hex-escape': 'warn',
      'unicorn/no-instanceof-array': 'warn',
      'unicorn/no-invalid-fetch-options': 'warn',
      'unicorn/no-invalid-remove-event-listener': 'warn',
      'unicorn/no-keyword-prefix': 'off',
      'unicorn/no-length-as-slice-end': 'warn',
      'unicorn/no-lonely-if': 'warn',
      'unicorn/no-magic-array-flat-depth': 'warn',
      'unicorn/no-negated-condition': 'warn',
      'unicorn/no-nested-ternary': 'warn',
      'unicorn/no-new-array': 'warn',
      'unicorn/no-new-buffer': 'warn',
      'unicorn/no-null': 'off',
      'unicorn/no-object-as-default-parameter': 'warn',
      'unicorn/no-process-exit': 'off',
      'unicorn/no-single-promise-in-promise-methods': 'warn',
      'unicorn/no-static-only-class': 'warn',
      'unicorn/no-thenable': 'warn',
      'unicorn/no-this-assignment': 'warn',
      'unicorn/no-typeof-undefined': 'warn',
      'unicorn/no-unnecessary-await': 'warn',
      'unicorn/no-unnecessary-polyfills': 'warn',
      'unicorn/no-unreadable-array-destructuring': 'warn',
      'unicorn/no-unreadable-iife': 'warn',
      'unicorn/no-unused-properties': 'warn',
      'unicorn/no-useless-fallback-in-spread': 'warn',
      'unicorn/no-useless-length-check': 'warn',
      'unicorn/no-useless-promise-resolve-reject': 'warn',
      'unicorn/no-useless-spread': 'warn',
      'unicorn/no-useless-switch-case': 'warn',
      'unicorn/no-useless-undefined': 'off',
      'unicorn/no-zero-fractions': 'warn',
      'unicorn/number-literal-case': 'warn',
      'unicorn/numeric-separators-style': 'warn',
      'unicorn/prefer-add-event-listener': 'warn',
      'unicorn/prefer-array-find': 'warn',
      'unicorn/prefer-array-flat': 'warn',
      'unicorn/prefer-array-flat-map': 'warn',
      'unicorn/prefer-array-index-of': 'warn',
      'unicorn/prefer-array-some': 'warn',
      'unicorn/prefer-at': 'warn',
      'unicorn/prefer-blob-reading-methods': 'warn',
      'unicorn/prefer-code-point': 'warn',
      'unicorn/prefer-date-now': 'warn',
      'unicorn/prefer-default-parameters': 'warn',
      'unicorn/prefer-dom-node-append': 'warn',
      'unicorn/prefer-dom-node-dataset': 'warn',
      'unicorn/prefer-dom-node-remove': 'warn',
      'unicorn/prefer-dom-node-text-content': 'warn',
      'unicorn/prefer-event-target': 'warn',
      'unicorn/prefer-export-from': 'warn',
      'unicorn/prefer-global-this': 'warn',
      'unicorn/prefer-includes': 'warn',
      'unicorn/prefer-json-parse-buffer': 'warn',
      'unicorn/prefer-keyboard-event-key': 'warn',
      'unicorn/prefer-logical-operator-over-ternary': 'warn',
      'unicorn/prefer-math-min-max': 'warn',
      'unicorn/prefer-math-trunc': 'warn',
      'unicorn/prefer-modern-dom-apis': 'warn',
      'unicorn/prefer-modern-math-apis': 'warn',
      'unicorn/prefer-module': 'warn',
      'unicorn/prefer-native-coercion-functions': 'warn',
      'unicorn/prefer-negative-index': 'warn',
      'unicorn/prefer-node-protocol': 'warn',
      'unicorn/prefer-number-properties': 'warn',
      'unicorn/prefer-object-from-entries': 'warn',
      'unicorn/prefer-optional-catch-binding': 'warn',
      'unicorn/prefer-prototype-methods': 'warn',
      'unicorn/prefer-query-selector': 'warn',
      'unicorn/prefer-reflect-apply': 'warn',
      'unicorn/prefer-regexp-test': 'warn',
      'unicorn/prefer-set-has': 'warn',
      'unicorn/prefer-set-size': 'warn',
      'unicorn/prefer-spread': 'off',
      'unicorn/prefer-string-raw': 'warn',
      'unicorn/prefer-string-replace-all': 'off',
      'unicorn/prefer-string-slice': 'warn',
      'unicorn/prefer-string-starts-ends-with': 'warn',
      'unicorn/prefer-string-trim-start-end': 'warn',
      'unicorn/prefer-structured-clone': 'warn',
      'unicorn/prefer-switch': 'warn',
      'unicorn/prefer-ternary': 'warn',
      'unicorn/prefer-top-level-await': 'warn',
      'unicorn/prefer-type-error': 'warn',
      'unicorn/prevent-abbreviations': 'off',
      'unicorn/relative-url-style': 'warn',
      'unicorn/require-array-join-separator': 'warn',
      'unicorn/require-number-to-fixed-digits-argument': 'warn',
      'unicorn/require-post-message-target-origin': 'warn',
      'unicorn/string-content': 'warn',
      'unicorn/switch-case-braces': 'warn',
      'unicorn/template-indent': 'warn',
      'unicorn/text-encoding-identifier-case': 'warn',
      'unicorn/throw-new-error': 'off',
    },
  },
  {
    plugins: {
      import: importPlugin,
    },
    rules: {
      'import/no-unresolved': 'off',
      'import/no-duplicates': 'off',
    },
    settings: {
      'import/resolver': {
        // You will also need to install and configure the TypeScript resolver
        // See also https://github.com/import-js/eslint-import-resolver-typescript#configuration
        typescript: true,
        node: true,
      },
    },
  },
  eslintConfigPrettier,
  {
    rules: {
      curly: ['warn', 'multi'],
    },
  },
  {
    plugins: {
      i18next: i18next,
    },
    rules: {
      'i18next/no-literal-string': [
        'warn',
        {
          ignore: ['data-', 'aria-', 'test-'],
          ignoreCallee: ['t', 'i18n.t'],
          ignoreAttribute: ['data-', 'aria-', 'test-'],
          ignoreProperty: ['data-', 'aria-', 'test-'],
          ignoreText: ['^[0-9]+$', '^[a-zA-Z0-9_]+$'],
        },
      ],
    },
  },
] satisfies Linter.Config[];
